[package]
name = "piscem-meta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libradicl = { git = "https://github.com/COMBINE-lab/libradicl", version = "0.4.6" }
ahash = "0.7.6"
anyhow = "1.0.57"
bincode = "1.3.3"
bstr = "0.2.17"
scroll = "0.11.0"
clap = { version = ">=3.2.14", features = ["derive", "wrap_help", "cargo"] }
slog = "2.7.0"
slog-term = "2.9.0"
slog-async = "2.7.0"
