[package]
name = "piscem-infer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libradicl = { git = "https://github.com/COMBINE-lab/libradicl", version = "0.5.0" }
ahash = "0.7.6"
anyhow = "1.0.66"
bincode = "1.3.3"
bstr = "1.0.1"
scroll = "0.11.0"
clap = { version = "~4.0.25", features = ["derive", "wrap_help", "cargo", "help", "usage", "error-context"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", default-features = true, features = ["env-filter"] }
tabled = "0.10.0"
