[package]
name = "piscem-infer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libradicl = { git = "https://github.com/COMBINE-lab/libradicl", version = "0.6.0" }
ahash = "0.8.3"
anyhow = "1.0.71"
bincode = "1.3.3"
bstr = "1.5.0"
scroll = "0.11.0"
clap = { version = "4.3.10", features = ["derive", "wrap_help", "cargo", "help", "usage", "error-context"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", default-features = true, features = ["env-filter"] }
tabled = "0.12.2"

[[bin]]
name = "piscem-infer"
path = "src/main.rs"

[profile.release]
debug-assertions = false
lto = "thin"
panic = "abort"
